export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASH_BURGER_START = 'PURCHASH_BURGER_START';
export const PURCHASH_BURGER_SUCCESS = 'PURCHASH_BURGER_SUCCESS';
export const PURCHASH_BURGER_FAIL = 'PURCHASH_BURGER_FAIL';
export const PURCHASH_INIT = 'PURCHASH_INIT';

export const FETCH_OREDRS_START = 'FETCH_OREDRS_START';
export const FETCH_OREDRS_SUCCESS = 'FETCH_OREDRS_SUCCESS';
export const FETCH_OREDRS_FAIL = 'FETCH_OREDRS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';